version: "3.8"

services:
  encurtador-backend:
    build: ./backend
    container_name: encurtador-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/encurtador
    depends_on:
      - mongo
    volumes:
      - ./backend/logs:/app/logs

  encurtador-frontend:
    build: ./frontend
    container_name: encurtador-frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - encurtador-backend

  mongo:
    image: mongo
    container_name: encurtador-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
